// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1MjSWHZcEzIBlvNvXbFZ3hj0cmMvbXAw',
    appId: '1:87076668498:web:42a3f32c99c96ecb1ecb8b',
    messagingSenderId: '87076668498',
    projectId: 'happy-chicken-e7368',
    authDomain: 'happy-chicken-e7368.firebaseapp.com',
    storageBucket: 'happy-chicken-e7368.firebasestorage.app',
    measurementId: 'G-TN6BTMQGL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX3TGUzXLbLGwNBC8Lz2owzLytViswvC8',
    appId: '1:87076668498:android:418f665839b905d81ecb8b',
    messagingSenderId: '87076668498',
    projectId: 'happy-chicken-e7368',
    storageBucket: 'happy-chicken-e7368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABEVF70tR1vBncVM5d8gUYjxizLPNzpxE',
    appId: '1:87076668498:ios:2d337ce4e2dbf7a51ecb8b',
    messagingSenderId: '87076668498',
    projectId: 'happy-chicken-e7368',
    storageBucket: 'happy-chicken-e7368.firebasestorage.app',
    iosBundleId: 'com.example.happyChickenRestaurant',
  );
}
